name: 'Bug report'
description: 'Create a report to help us improve GlideLite'
body:
  - type: markdown
    attributes:
      value: |
        🔍 Please [search thoroughly in GitHub](https://github.com/sanderveldhuis/glidelite/search?type=Issues) or by the query `site:github.com/sanderveldhuis/glidelite <your keywords>` in your favorite search engine before reporting a new bug as most bugs are very likely to find precedents.

        Please fill in each section completely. Thank you!
  - type: textarea
    id: search_terms
    attributes:
      label: '🔎 Search Terms'
      description: |
        What search terms did you use when trying to find an existing bug report?

        List them here so people in the future can find this one more easily.
      placeholder: |
        List of keywords you searched for before creating this issue. Write them down here so that others can find this bug more easily and help provide feedback.
    validations:
      required: true
  - type: textarea
    id: version_info
    attributes:
      label: '🕗 Version & Regression Information'
      description: |
        When did you start seeing this bug occur?

        Please try the nightly version of GlideLite to see if it's already been fixed. Install `sanderveldhuis/glidelite#next`.

        Please keep and fill in the line that best applies.
      value: |
        - This changed between versions ______ and _______
        - This changed in commit or PR _______
        - This is the behavior in every version I tried
        - I was unable to test this on prior versions because _______
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: 💻 Code
      description: |
        Please post the relevant code sample here as well.

        We can quickly address your report if:

          - The code sample is short.
          - It doesn't use external libraries.
          - The incorrectness of the behavior is readily apparent from reading the sample.

        Reports are slower to investigate if:

          - We have to pare too much extraneous code.
          - We have to clone a large repo and validate that the problem isn't elsewhere.
          - The sample is confusing or doesn't clearly demonstrate what's wrong.
      value: |
        ```ts
        // Your code here
        ```
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: 🙁 Actual behavior
      description: 'What happened, and why it was wrong.'
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: 🙂 Expected behavior
      description: What you expected to happen instead, and why
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information about the issue
