name: Nightly Build

on:
  schedule:
    - cron: '0 4 * * *'
  # enable users to manually trigger with workflow_dispatch
  workflow_dispatch: {}

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'sanderveldhuis/glidelite'

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
      - name: Setup and test nightly
        run: |
          npm ci
          npm run dist

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.repository == 'sanderveldhuis/glidelite'

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: next
          fetch-depth: 0
          token: ${{ secrets.PUSH_GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
      - name: Setup Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Rebase branch
        run: |
          git rebase origin/main
          git push -f origin next
      - name: Setup and build nightly
        run: |
          npm ci
          npm run dist
      - name: Push changes
        # Force adding the lib folder because it is required for releases
        run: |
          git diff
          git add --force lib
          git commit -m "Nightly build" || echo "No changes to commit"
          git push
